language: julia

os: linux
julia:
  - 1
  - nightly



notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

jobs:
  allow_failures:
    - julia: nightly
